# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sendrecv < Formula
  desc "Repeat SSH-based file transfer between known devices"
  homepage "https://github.com/connorpink/quick_send_project"
  version "0.1.4"
  license "MIT"

  depends_on "rsync"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorpink/quick_send_project/releases/download/v0.1.4/sendrecv_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5d7f3cffdb1b433bf313f07ed559fc8e5108afd56266547767a6653c010276c8"

      define_method(:install) do
        bin.install "sendrecv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorpink/quick_send_project/releases/download/v0.1.4/sendrecv_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ecced58b44bfdca2d75d82844fb30f44f2099a45bc046e1511219164d40cd272"

      define_method(:install) do
        bin.install "sendrecv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorpink/quick_send_project/releases/download/v0.1.4/sendrecv_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c8b83e5294bab772a28e57052064254590640bf4dc7c4c3a607241367c0ae0eb"
      define_method(:install) do
        bin.install "sendrecv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/connorpink/quick_send_project/releases/download/v0.1.4/sendrecv_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "08a1c71b54d97f1470258595cad4cd53894f7014943753f0ee57e26b0a21416e"
      define_method(:install) do
        bin.install "sendrecv"
      end
    end
  end
end
